export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_STE_LIST = "GET_STE_LIST";
export const GET_STE_LIST_SUCCESS = "GET_STE_LIST_SUCCESS";

export const GET_CENTER_LIST = "GET_CENTER_LIST";
export const GET_CENTER_LIST_SUCCESS = "GET_CENTER_LIST_SUCCESS";

export const GET_DOMAIN_LIST = "GET_DOMAIN_LIST";
export const GET_DOMAIN_LIST_SUCCESS = "GET_DOMAIN_LIST_SUCCESS";

export const GET_FORMATION_LIST = "GET_FORMATION_LIST";
export const GET_FORMATION_LIST_SUCCESS = "GET_FORMATION_LIST_SUCCESS";
